export const ROUTE = {
  // login: "/login",
  login: "",
  customerDashboard: "/dashboard/customer",
  customerTicket: "/dashboard/customer/ticket",
  customerTicketDetail: "/dashboard/customer/ticket/:ticketId",
  customerHistory: "/dashboard/customer/history",
  agentDashboard: "/dashboard/csAgent",
  agentTicket: "/dashboard/csAgent/ticket",
  technicianDashboard: "/dashboard/technician",
  ultrauserDashboard: "/ultrauser/dashboard",
  ultrauserTicket: "/ultrauser/ticket",
  ultrauserTicketCustomer: "/ultrauser/ticket/customer",
  ultrauserTicketCustomerDetail: "/ultrauser/ticket/customer/:ticketId",
  ultrauserTicketAgent: "/ultrauser/ticket/agent",
  ultrauserTicketTechnician: "/ultrauser/ticket/technician",
  ultrauserTicketAdmin: "/ultrauser/ticket/admin",
  ultrauserHistory: "/ultrauser/history",
  ultrauserHistoryCustomer: "/ultrauser/history/customer",
  ultrauserHistoryAgent: "/ultrauser/history/agent",
  ultrauserHistoryTechnician: "/ultrauser/history/technician",
  ultrauserHistoryAdmin: "/ultrauser/history/admin",
  ultrauserMenu: "/ultrauser/menu",
  ultrauserUsers: "/ultrauser/users",
  ultrauserCompany: "/ultrauser/company",
};
