export const ROUTE = {
  // login: "/login",
  login: "",
  customerDashboard: "/dashboard/customer",
  customerTicket: "/dashboard/customer/ticket",
  customerTicketDetail: "/dashboard/customer/ticket/:ticketId", // ticket details
  customerHistory: "/dashboard/customer/history",
  agentDashboard: "/dashboard/csAgent",
  agentTicket: "/dashboard/csAgent/ticket",
  agentPerformance: "/dashboard/csAgent/performance",
  agentTicketDetail: "/dashboard/csAgent/ticket/:ticketId", // ticket details
  technicianDashboard: "/dashboard/technician",
  technicianTicket: "/dashboard/technician/ticket",
  technicianTicketDetail: "/dashboard/technician/ticket/:ticketId",
  technicianPerformance: "/dashboard/technician/performance",
  ultrauserDashboard: "/ultrauser/dashboard",
  ultrauserTicket: "/ultrauser/ticket",
  ultrauserTicketCustomer: "/ultrauser/ticket/customer",
  ultrauserTicketCustomerDetail: "/ultrauser/ticket/customer/:ticketId", // ticket details
  ultrauserTicketAgent: "/ultrauser/ticket/agent",
  ultrauserTicketTechnician: "/ultrauser/ticket/technician",
  ultrauserTicketAdmin: "/ultrauser/ticket/admin",
  ultrauserHistory: "/ultrauser/history",
  ultrauserHistoryCustomer: "/ultrauser/history/customer",
  ultrauserHistoryAgent: "/ultrauser/history/agent",
  ultrauserHistoryTechnician: "/ultrauser/history/technician",
  ultrauserHistoryAdmin: "/ultrauser/history/admin",
  ultrauserMenu: "/ultrauser/menu",
  ultrauserUsers: "/ultrauser/users",
  ultrauserCompany: "/ultrauser/company",
  adminDashboard: "/dashboard/admin",
  adminTicket: "/dashboard/admin/ticket",
  adminUserPerformance: "/dashboard/admin/performance",
  customerProfile: "/profile/customer",
  agentProfile: "/profile/csAgent",
  technicianProfile: "/profile/technician",
  adminProfile: "/profile/admin",
};
